# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default=None, max_length=20, null=True)),
                ('pincode', models.CharField(default=None, max_length=6, null=True)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('uts', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
