# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='shotcode',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='pincode',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
