# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20161229_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='country',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
