# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_station_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='state',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
