# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_station_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='shotcode',
            new_name='statecode',
        ),
        migrations.RemoveField(
            model_name='station',
            name='state',
        ),
    ]
