# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_auto_20161229_1725'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='station',
            unique_together=set([('city', 'statecode', 'country')]),
        ),
    ]
