# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_auto_20161229_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='pincode',
        ),
        migrations.AddField(
            model_name='station',
            name='lat',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='long',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
